### ISSUE TITLE
CrashMonkey test faililng due to assertion error in RandomPermuter

### ISSUE THREAD

**Issue by pandian4github** [utsaslab/crashmonkey#105]
Many times, the crash monkey test fails with an assertion error in random permuter due to which it is unable to decide the result of the test.  The error looks like -

`c_harness: permuter/RandomPermuter.cpp:307: void fs_testing::permuter::RandomPermuter::AddEpochs(const iterator&, const iterator&, const iterator&, const iterator&): Assertion 'current_res != res_end' failed.`

We noticed this happens more frequently while testing for ext4 than the other file systems.

**Comment by vijay03** [comment]
Should be fixed by @ashmrtn's patch: #106
