### ISSUE TITLE
Kernel modules and C++

### ISSUE THREAD

**Issue by domingues** [utsaslab/crashmonkey#11]
So it seems there is no support to C++, I was trying to port the code to Kernel 3.16 and an included header in the compilation of `RandomPermuter.so` (`linux/stddef.h`) try to define `true` and `false`, that are keywords in C++.
A workaround is remove the link to the kernel headers in the compilation of `RandomPermuter.so`, and create a local file with a copy of the needed values from `linux/blk_types.h`. But I don't like it.

**Comment by ashmrtn** [comment]
Huh, I'm actually quite surprised I didn't run into that earlier. I think what we should do is partition our design a bit more. Why don't you try making a C file that defines methods that take a `disk_write_op_meta` and return a bool for the various operation types I have defined in `utils.cpp`? The new C file can then safely include the kernel header, and the C++ files can include a new header that declares the new C methods. So what you will end up with is something like:

```c
<new header file>
bool is_async_write(struct disk_write_op_meta* m);
bool is_barrier_write(struct disk_write_op_meta* m);
bool is_meta(struct disk_write_op_meta* m);
bool has_write_flag(struct disk_write_op_meta* m);
```

The C file will then have the implementations of the functions in the new header file. `utils.cpp` can then include the new header file without pulling in the include for `stddef.h` (or at least that is my hope....).

**Comment by domingues** [comment]
Fixed by commit b10f26e7a03c8a9daefdb5c51c86065bfbaa6962.

**Comment by vijay03** [comment]
@domingues, you should send @ashmrtn a pull request, that way she can review the code before merging it. Is the newly ported version backwards-compatible with the kernel we were using before?

**Comment by ashmrtn** [comment]
We will need to add guards or something around code that is specific to 4.4 and the original code in the kernel modules. The way that `bio`s are handled has changed between the two kernel versions. We may also need to check that the flag fields the `disk_wrapper` module logs are correct.

**Comment by ashmrtn** [comment]
I will post comments when branch is PR-ed so it is easier to see things all at once.
