### ISSUE TITLE
Implement Checkpoints

### ISSUE THREAD

**Issue by vijay03** [utsaslab/crashmonkey#12]
I have a long email thread in my inbox with @ashmrtn about this. Will add the summary from that thread here later.

In short, we want to have some mechanism to know what data/metadata to expect in each crash state. The idea is to allow users to call Checkpoint, which captures the user-visible state (directory tree + data) of the file system somewhere. On a crash, we go back to the latest Checkpoint and see if we have all the data in there.

**Comment by ashmrtn** [comment]
To summarize the email chain, we were thinking that we could use checksums to help us save the user-visible state when Checkpoint is called. For simplicity, we could likely use a hashmap keyed on file paths whose values are the checksums. Each checkpoint could generate a hashmap by walking the directory structure of the file system and checksumming the files found.

**Comment by ashmrtn** [comment]
We may also want to checksum at least some of the data available from calls to `stat()` (ex. file size and permissions but none of the modified/accessed/created times) so that we can catch user-visible metadata errors as well. @vijay03 may have meant that when he said "(directory tree + data)", but I would like to explicitly put that out there as well.

**Comment by ashmrtn** [comment]
We also need to be able to associate checkpoints with points in our logged `bio` sequence so we should timestamp when the checkpoint was done. Logged `bio`s will also need timestamps as that information is not currently recorded.

We can assume that the user has just completed a `sync` operation of some form when `Checkpoint()` is called.

**Comment by vijay03** [comment]
Sockets sounds reasonable. To associate Checkpoints with the stream of data sent to the device, we should have either a file inside the device (lets say called Flag), that is written to everytime there is a checkpoint. Using writes to Flag, we can then associate each checkpoint in the dat stream. 

Another approach would be to have a in-kernel counter that is incremented every time the user calls Checkpoint (via an ioctl for example). Using the counter we associate checkpoints with bios.

**Comment by vijay03** [comment]
@domingues @ashmrtn progress seem to have stalled on this? Are we blocked on something?

**Comment by domingues** [comment]
I have two doubts by now:
1. Should I ignore `lost+found` folder?
2. So on every crash tested (`test_check_random_permutations()`) if the user test fails (`test_loader.get_instance()->check_test()`) we should check if the data is equal to the last checkpoint made?

**Comment by vijay03** [comment]
Lets ignore lost and found for now.

By "user test", do you mean a test that the user runs on top of the mounted file system? If so, this is the default version of that user test. Once the file system mounts, we are basically testing that the data/metadata we expect is in there.

If the file system does not mount at all, we just report an error and return.

**Comment by vijay03** [comment]
I think implementing checkpoints is a very large task, that is unlikely to be merged in with a single pull request. @domingues, could you merge in parts of it with pull requests as you code it up?

**Comment by ashmrtn** [comment]
@vijay03 I think it might be advantageous to split the functionality of the original checkpoint idea into 2 things:
1. a `checkpoint` type operation that will be passed to user tests, denoting the most recent checkpoint reached in the generated crash state (only available after sync/fsync)
1. a `watch` type operation where the user passes a file path to CrashMonkey and CrashMonkey then monitors that file path to make sure no changes occur in it after that point in generated crash states. This will require support from (1) as well. (only available after sync/fsync)

**Comment by ashmrtn** [comment]
I'm going to split this issue up into several smaller ones since both checkpoints and watches somewhat complicated and require support across different parts of CrashMonkey.

**Comment by vijay03** [comment]
Should we close this issue now @ashmrtn ?
