### ISSUE TITLE
ACE fails on fsync

### ISSUE THREAD

**Issue by squizz617** [utsaslab/crashmonkey#124]
Hi,

If I include `fsync` in the OperationSet list (`ace/ace.py` line 59), and run (`python ace.py -l 1 -n False -d False`), ACE fails with the following error message:
```
Traceback (most recent call last):
  File "ace.py", line 1463, in <module>
    main()
  File "ace.py", line 1422, in main
    doPermutation(i)
  File "ace.py", line 1242, in doPermutation
    cur_line = buildJlang(modified_sequence[insert], length_map)
  File "ace.py", line 1017, in buildJlang
    ret = flat_list[2]
IndexError: list index out of range
```

Thanks.

**Comment by vijay03** [comment]
We handle fsync of files in the workload separately: after each operation, Ace will generate fsync(), fdatasync(), or sync() on one of the workset files. Not sure if we need fsync() in the OperationSet list.

@jayashreemohan29, can you confirm?

**Comment by squizz617** [comment]
I see your point, professor Vijay.
I had a false impression from the comment ("Set of file-system operations to be used in test generation") that sync and fsync should be in the OperationSet list, but just found that either `fsync()` or `sync()` is auto-generated on one of the open files even though they're not in the list.
Thank you!

**Comment by vijay03** [comment]
Great! Closing this issue then.
