### ISSUE TITLE
Build error happening 

### ISSUE THREAD

**Issue by Puthranps** [utsaslab/crashmonkey#131]
While building it's detecting syntax error such as implicit function declarations. 

declaration of function ‘get_disk’; did you mean ‘put_disk’? [-Werror=implicit-function-declaration]
   kobj = brd ? get_disk(brd->brd_disk) : NULL;

I have installed all dependencies and am running on Ubuntu 18.10

**Comment by ashmrtn** [comment]
Which kernel version are you running on (can be viewed with `uname -r`)? `cow_brd.c` is a kernel module, so the warnings/errors you're seeing are related to changes in kernel versions. If you don't want to deal with this issue, you can switch to one of the supported kernel versions which is listed [here](https://github.com/utsaslab/crashmonkey/blob/master/docs/CrashMonkey.md#setting-up-a-vm). You can easily download .debs of different kernels from the [Ubuntu kernel ppa](https://kernel.ubuntu.com/~kernel-ppa/mainline/) which can then be installed with `dpkg`. Please note that you will also have to get the deb file with the kernel headers as well as those are required to compile kernel modules in CrashMonkey.

**Comment by Puthranps** [comment]
I have kernel version 4.18 I can try different .Deb for my Linux version.
