### ISSUE TITLE
Memory access violation

### ISSUE THREAD

**Issue by jcyuan78** [utsaslab/crashmonkey#142]
In the DiskMod::GetSerializeSize() in DiskMod.cpp lines 25-28, for type==kRemoveMod, the function just return the request memory size as 13 byte + path size, not include the length and offset of the payload data.
However, in  DiskMode::Serialize() in DiskMode.cpp line 115-117, when the type == kRemoveMod, it will continue to call SerializeDataRange(), which write additional 16 bytes to the buffer. This may causes memory overflow. 
We suggest adding condition dm.mod_type==DiskMode::kRemoveMod in line 115.

**Comment by ashmrtn** [comment]
Thanks for pointing this out!
