### ISSUE TITLE
Redo Makefile

### ISSUE THREAD

**Issue by ashmrtn** [utsaslab/crashmonkey#15]
Now that the project is getting bigger, the Makefile should be modified so that builds are cleaner.

Included code should be compiled into libraries where possible and linked where needed instead of provided directly as it is now.

Compiled code should also be placed in its own `build` directory instead of alongside the source files which generated it. This will make `make clean` much easier to define as well as making it easier to avoid checking in binaries in git.

**Comment by vijay03** [comment]
@ashmrtn , is this done, should we close this issue?

**Comment by ashmrtn** [comment]
I am hesitant to call it finished. I would really like to switch to something like CMake or Bazel (though Bazel unfortunately has a Java dependency). That way it's a little less cryptic (at least that is my hope). I have kind of been switching stuff over to "cleaner" Make statements, although they are regrettably much more cryptic than the ones that existed before them.

**Comment by vijay03** [comment]
My personal opinion is that your current Makefile is fine :) We should definitely not use anything related to Java, and I often CMake makes things harder to understand, not easier.

**Comment by ashmrtn** [comment]
That's kind of a shame, I had hoped there would be something that would provide a rather readable build file. Anyway, I guess we should kind of shuffle the remaining items over to build in the `build` directory. Some of the variables/target names may need a bit of cleaning up too, now that I think of it.

**Comment by vijay03** [comment]
Alright, do you want to handle it yourself? It might be a good warm-up task for Sonika.

**Comment by ashmrtn** [comment]
I can pick up this task.
