### ISSUE TITLE
Allow User Data Consistency Test to Output Meaningful Errors

### ISSUE THREAD

**Issue by ashmrtn** [utsaslab/crashmonkey#17]
The current system is a simple pass/fail return from user data consistency tests. We need to update this to allow user data consistency tests to output meaningful errors that help with finding file system bugs. Without this, it is not easy to determine why a test failed since you can only see summary information about the tests.

**Comment by vijay03** [comment]
Yes, this is certainly something we need to handle going forward. 

I'd expect the error output to have the following:
1. The error. This could be "Files Missing", "Files Corrupted", "Accounting Wrong" (for double counting references or not counting them at all), or "Unmountable"
2. The particular crash test that resulted in the error. This might be details like epoch prefix and the particular permutation that has been applied. (TODO for later: build a utility that given this information and the base state, will produce the crash state). 

Note that if fsck fixes errors in the state (like detecting and fixing a resource leak), we do want to report those, but at a "warning" level rather than a "error" level.

**Comment by ashmrtn** [comment]
Yes, I agree that we will need to provide all the information you listed above. I think what we should think about is a sort of multi-tiered approach.

We should have user data consistency tests return a generic error code like the one you listed above in part (1). However, they should also be given the opportunity to put a string in a returned error object which can then be printed out to logs. This allows users some area to put specific information in, like the file that caused the error. After all, just knowing what sort of error occurred on a file system with 100+ files doesn't help very much.

Next, the Permuters should adhere to, and provide, an interface that allows the main test harness to obtain information about the most recently generated crash state. This could, again, have a basic string field that we can stick information like the RNG seed etc. in if desired. This allows for reproducibility (if RNG seeds are output) as well as providing extra information.

These interfaces can be used to print extra information in the event of an error. The interface on the Permuters can also be used to dump extra data to logs on any run if users want it.

**Comment by vijay03** [comment]
Yup, I agree each error should have a error number and an associated string. Your design looks reasonable.

**Comment by ashmrtn** [comment]
#20 brought in a basic error model for CrashMonkey. However, this still does not allow users to report meaningful errors. The current error model should be expanded to write more specific, user provided errors to a log file for later review.

Most changes will likely be in the `DataTestResult` class to support a user string describing the error. A function should also be added to the `Tester` class to write the user provided error out to the provided stream (a call in `c_harness.c` can be used to output the log before exiting the test harness).

A log entry should look similar to the following (I'm flexible on the exact formatting, but it should at least contain the information below)
```
test #1: FAILED file_missing: mnt/snapshot/test_dir/test_file is missing
```
In the above example, `mnt/snapshot/test_dir/test_file is missing` is the user provided message. The other information should already be present in the `TestSuiteResult` or `DataTestResult` classes.

**Comment by ashmrtn** [comment]
log file names should include the test case being run and some sort of date/timestamp so that they are unique even if a test case is run multiple times
ex.
```
20170819_123456-rename_root_to_sub.log
```
where the part before the `-` is a date/timestamp of some sort (like system jiffies and/or date string including year, month, day, and hour, minutes, seconds if jiffies aren't used) and the part after the `-` is the name of the test case being run.
