### ISSUE TITLE
Reproduce file-system bugs found on mailing lists

### ISSUE THREAD

**Issue by ashmrtn** [utsaslab/crashmonkey#24]
Recently, a couple of gentlemen have been using `dm-log-writes` and `xfstests` (available [here](https://github.com/amir73il/xfstests/tree/dm-log-writes)). We should reproduce these bugs in CrashMonkey as well.

**Comment by ashmrtn** [comment]
@vijay03 I am working on getting an email out to the original finder of the bug about this. It appears that he put another test case out and I am working on adding that to CrashMonkey to make sure we can reproduce it as well.

**Comment by ashmrtn** [comment]
efd486695ead2d68795b191693a12a2e01b2a058 updates CrashMonkey with a jerry-rigged port of the ext4 regression bug found.

**Comment by ashmrtn** [comment]
An `xfs` bug was also found that we should seek to reproduce.
https://marc.info/?l=linux-fsdevel&m=150421026009701&w=2

**Comment by vijay03** [comment]
The xfs bug is subtle and demonstrates why we need something like CrashMonkey very nicely. We should definitely reproduce this. I've made a [wiki page](https://github.com/utsaslab/crashmonkey/wiki/Kernel-Threads-to-Follow) where I am collecting interesting mailing lists conversations like this to follow.

**Comment by ashmrtn** [comment]
It looks like xfs may be a good target to test. Our friends with dm-log-writes put out another patch to `fstests` and `linux-xfs` lists with subject of  "[RFC][PATCH]fstests: regression test for xfs leftover CoW extent error" (will update with link when archives pick it up).

Sounds like this one is just an error with the file system overall, it doesn't need a crash to reproduce.

**Comment by ashmrtn** [comment]
Our friends with dm-log-writes seem to have been poking at overlayfs too. It seems like they might be trying to just run dm-log-writes on all the file systems they can get their hands on.

Information on overlayfs can be found [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/overlayfs.txt). The bug patch name is "[PATCH 0/2] overlay: fix INDEX=y regressions" (I am unable to link to the gmane mailing list directly).

**Comment by ashmrtn** [comment]
This is not a bug found by dm-log-writes, but it looks like someone found a [bug in the disk usage accounting](https://marc.info/?l=linux-xfs&m=150650533622909&w=2). This appears in ext4 and xfs, but only in 4/10 of the tests they run, making it seem like xfstests is having a hard time finding it consistently. This is running on kernel 4.14-rc1.

**Comment by ashmrtn** [comment]
9p bug: https://marc.info/?l=linux-netdev&m=150853032419362&w=2

**Comment by ashmrtn** [comment]
xfs recovery bug: https://marc.info/?l=linux-xfs&m=150836989009464&w=2

**Comment by ashmrtn** [comment]
btrfs metadata accounting bug: https://mail-archive.com/linux-btrfs@vger.kernel.org/msg69423.html

**Comment by ashmrtn** [comment]
This ext4 bug seems like it may be a good candidate for reproduction. It has to do with `fdatasync` and `fallocate` causing blocks to go missing: https://marc.info/?l=linux-ext4&m=151074688620892&w=2

**Comment by ashmrtn** [comment]
not a crash consistency bug per se, but it may be something we could look into:
1/2: https://mail-archive.com/linux-btrfs@vger.kernel.org/msg72612.html
2/2: https://mail-archive.com/linux-btrfs@vger.kernel.org/msg72611.html

**Comment by ashmrtn** [comment]
This is more of a theoretical thing that could happen, but may be something we can look into in the future as it deals with both a computer crash and hardware corruption of data (for F2FS):
https://sourceforge.net/p/linux-f2fs/mailman/message/36196800/

**Comment by ashmrtn** [comment]
Sounds kind of like the delayed allocation ext4 bug we explored earlier, but this time with direct writes:
https://marc.info/?l=linux-ext4&m=151669669030547&w=2

**Comment by ashmrtn** [comment]
Another f2fs bug. This one sounds more like it could occur when bios are split, but I'm not exactly sure just from reading the summary:
https://sourceforge.net/p/linux-f2fs/mailman/message/36204985/

**Comment by vijay03** [comment]
Right, the latest F2FS bug seems like it would be easily reproducible. @jayashreemohan29

**Comment by ashmrtn** [comment]
We may have to play with maximum bio size a little bit in CrashMonkey to figure that one out, but it is definitely possible. From the cited email, it sounds almost like they are worried about a bio being split, but I have not researched that further

**Comment by ashmrtn** [comment]
This is not a file system bug that requires a crash, but it may be something we can reproduce with CrashMonkey (XFS file system): https://marc.info/?l=fstests&m=151792263511472&w=2

It sounds like they are mostly moving extents around in files, though I haven't investigated further

**Comment by ashmrtn** [comment]
not a specific btrfs issue, but maybe something to look into/think about:
https://mail-archive.com/linux-btrfs@vger.kernel.org/msg73465.html

**Comment by ashmrtn** [comment]
I'm not sure exactly what feature of xfs this is fixing (swapext), but it seems like something that we would be interested in demonstrating:
https://www.spinics.net/lists/linux-xfs/msg15923.html

**Comment by ashmrtn** [comment]
Btrfs hole punch bug:

**Comment by ashmrtn** [comment]
Test for preserving extents after fallocate and fsync:
https://marc.info/?l=fstests&m=152300088118055&w=2

**Comment by ashmrtn** [comment]
this patch for DIO hasn't landed yet, but it may be worth checking out in the future: https://marc.info/?l=linux-block&m=152402498811127&w=2
