### ISSUE TITLE
Have a set of tests run against each file system

### ISSUE THREAD

**Issue by vijay03** [utsaslab/crashmonkey#3]

**Comment by vijay03** [comment]
1. Test mmap() and file read()/write() at the same time
2. Test crashes in the middle of rename
3. Truncating a file, then creating another file

**Comment by vijay03** [comment]
4. Allocate resources such as inodes and data blocks until file system is 95% full. Then crash in the middle of workloads which allocate a resource, then deallocate the resource, repeatedly. 
5. Modify xfstests for crash testing

**Comment by ashmrtn** [comment]
For file systems that journal data, we should profile/test workloads where we fill the journal up so that it is forced to write it out

**Comment by vijay03** [comment]
Agreed. In general I think our setup should always push the file system to the brink of resource exhaustion (90% space used, smallest journal possible etc) and then run our tests.
