### ISSUE TITLE
Collect crash-consistency bugs to reproduce

### ISSUE THREAD

**Issue by vijay03** [utsaslab/crashmonkey#5]
Look at Linux kernel mailing lists and file-system specific lists such as linux-ext4 and linux-btrfs to collect bugs we could attempt to reproduce.

**Comment by vijay03** [comment]
Related paper to read: https://www.usenix.org/system/files/conference/hotstorage17/hotstorage17-paper-gatla.pdf. So we might try something like: crash the system, start CrashMonkey logging, do journal recovery in ext4, stop CrashMonkey logging. Then we will construct crash states in the middle of journal recovery. 

To do this, I guess what is missing in current infrastructure is being able to start logging just before the journal recovery happens and stop logging after that. @ashmrtn ?

**Comment by ashmrtn** [comment]
Correct, we are currently missing the infrastructure to do this. However, the infrastructure required to perform a test like the one you just described is a little more complex than the infrastructure originally discussed in #1. The infrastructure we are talking about here cannot assume that the RAM block device is used to create the original disk image as that would not survive the crash. Therefore, I will have to spend a little more time putting all the pieces together to make all the smaller pieces of CrashMonkey that work together to run the test.

**Comment by vijay03** [comment]
@ashmrtn could you elaborate on why "The infrastructure we are talking about here cannot assume that the RAM block device is used to create the original disk image as that would not survive the crash"? From our viewpoint, aren't all workloads the same? Just writes to the custom block device?

**Comment by ashmrtn** [comment]
Yes, but we will have to create a simple script or something to copy the data over to the RAM block device so we can get the starting state for the tests and the snapshot if we are really going to generate our test file system that needs recovery by crashing the machine. Even if we don't do that, we will have to throw together at least something to setup the initial state of the RAM block device.

**Comment by vijay03** [comment]
Ah I see. But couldn't we simulate the original crash as well? I'm thinking of something like this:
1. We run some workload
2. Construct a crash state in the middle of step 1
3. Mount file system on top of crash state
4. Now while file-system does recovery, capturing those IOs, and construct new crash states based on those.

We just have to do two levels of crash-state construction I think.

**Comment by ashmrtn** [comment]
Yes, that sounds possible. When we get that far, we will have to work out the exact details of how to construct a crash state from the crash state meant to run the recovery, but it should be doable.

If we really need results what we could do is actually crash a VM to construct a crash state, `dd` that state to a file for later use, and then make a small shim script which will `dd` the contents of the file onto the RAM block device in CrashMonkey's setup phase and then allow `fsck` or another program to work on it during the workload phase. (You can also substitute `dd` with any other means of simply copying the block device contents)

**Comment by vijay03** [comment]
Yes, I see what you mean. Feel free to actual crash+grab the state via <code>dd</code> to start with.
