### ISSUE TITLE
Use xfstests to create a test suite

### ISSUE THREAD

**Issue by vijay03** [utsaslab/crashmonkey#57]
https://github.com/kdave/xfstests

Infrastructure to do the following:
- Pick an xfstest
- Run in bkgd, profile with crashmonkey
- check N crash states

**Comment by gk159yo** [comment]
@vijay03 
@ashmrtn 

Our understanding of the issue at hand is that you want to be able to log operations for tests run by xfstest through crashmonkey. We are thinking of doing this by setting the crashmonkey wrapper device (hwm) to be the device that xfstest runs tests on.

We would like to request several clarifications. Is the above interpretation correct? As for "run in bkgd," does this mean to run xfstests in the background?

Also, we are confused about the last task: "check N crash states." Does this mean crashing the tests run by xfstest, and letting crashmonkey validate the state of the device afterward? Should we adjust how xfstests runs the requested test?

**Comment by ashmrtn** [comment]
Yes, making xfstests run it's tests on the CrashMonkey wrapper device is the proper approach. You will likely need to  check how large a disk xfstests wants to use. CrashMonkey thus far has been using pure RAM disks, so the file system size has been limited by system memory size.

I believe "run in bkgd" refers to running CrashMonkey in the background and then starting an xfstest with the CrashMonkey device wrapper.

"Checking N crash states" should just require you to change the `-s` parameter in CrashMonkey that denotes how many crash states to generate and test. You may also want to change the random seed in `RandomPermuter.cpp` to something actually random. Right now it is set to a fixed value to help with reproducibility.
