### ISSUE TITLE
Update CrashMonkey to also work with 4.x version kernels.

### ISSUE THREAD

**Issue by ashmrtn** [utsaslab/crashmonkey#6]
CrashMonkey currently only works with 3.x versions of the Linux kernel. It should be updated to work with 4.x versions of the kernel as well.

**Comment by vijay03** [comment]
@domingues would you like to work on this as a sort of warm-up project? It should make you familiar with all parts of the codebase.

**Comment by ashmrtn** [comment]
I believe the main portions of the codebase that you will need to look into for this are the kernel modules. The `cow_brd` module is a bit cleaner, though a tad more complex. That module is a modification of the `brd` module inside the Linux kernel. The `device_wrapper` module is something I threw together and, although it is conceptually simpler, may not be as clear since it was the first kernel module I've made.

**Comment by domingues** [comment]
@vijay03 Ok!

**Comment by domingues** [comment]
@ashmrtn could you please review the commit b10f26e7a03c8a9daefdb5c51c86065bfbaa6962, including the makefile?
